### ISSUE TITLE
not working on laptop without battery

### ISSUE THREAD

**Issue by aaronrancsik** [LorenzoMorelli/GPU_profile_selector#1]
- My laptop has no battery (temporary since the old is died).
- Therefore there is no battery option in gnome right corner menu.
- I guess  the extension is not show up because of this.

At extension "on" toggle I can see the following journal logs pop up:
`gnome-shell[53239]: clutter_actor_remove_child: assertion 'child->priv->parent != NULL' failed`

**Comment by LorenzoMorelli** [comment]
Yes you are probably right. Since there isn't any battery button in the right corner menu the extension fails to load.

I think a good workaround could be to move the extension button in the topbar instead of the right corner menu in the case the battery section is "not available".

I guess this alternative of the file "extension.js" should solve the issue.

As soon as possible (after weekend) I'll share a new version for solving this issue here.
Since I don't have the possibility to remove battery from my laptop, can you test it? I would be really grateful.

**Comment by aaronrancsik** [comment]
Of course, thank you very much!

**Comment by LorenzoMorelli** [comment]
Hi, I updated a new version that solves this issue. I would be pleased if you will give me a feedback!
The update will be available on official Gnome-shell Extension official website in few days I guess.
If everything works and then I'm going to close this issue, let me know!!

**Comment by aaronrancsik** [comment]
Hi, thank you! It's working fine!
