### ISSUE TITLE
[Criticism / Feature request]Options should default to no or ask the user

### ISSUE THREAD

**Issue by Marc-Pierre-Barbier** [LorenzoMorelli/GPU_profile_selector#6]
If i understood the code properly, this extension accept question envycontrol ask by "y". but some options such as fullcomposition pipeline can have a negative impact on latency in game. and i don't believe that enabling coolbits should be the default behavior.

A temp fix would be to replace "yes" by "yes n". But it's not a real solution.

A better one would be to add a way of choosing which options we want. asking the user can be done using a config file and a pop-up.

**Comment by LorenzoMorelli** [comment]
Hi, I think you are right, it should be up to the user to choose which options enable and which disable. I think the best way it is to implement a setting panel editable from the gnome extension manager. Since I'm busy in this period, I would appreciate a lot if someone would like to do a PR. For the moment, I mark this as Requesting Feature.

**Comment by LorenzoMorelli** [comment]
Hi!
I just implemented the settings view for the extension. So now you can access the settings by the gnome extension manager and set whichever flags you prefer for each mode.
